!include ../go.just

CDK_DEFAULT_ACCOUNT := `aws sts get-caller-identity --query Account --output text`
CDK_DEFAULT_REGION := `aws configure get region`

set fallback

synth:
  npx cdk synth

deploy:
  npx cdk deploy

diff:
  npx cdk diff

destroy:
  npx cdk destroy

bootstrap:
  npx cdk bootstrap